### ISSUE TITLE
Loading Image

### ISSUE THREAD

**Issue by jameschartouni** [killthekitten/kaggle-ds-bowl-2018-baseline#6]
I am trying to load images for data augmentation by passing one of the image ids, but 'None' is being returned. Am I using the wrong id? If I can get the image augmentation and data preprocessing working, I can submit an updated train.py.  

```python
# Training dataset
dataset_train = BowlDataset()
dataset_train.load_bowl('../../data/stage1_train')
dataset_train.prepare()

# # Validation dataset
dataset_val = BowlDataset()
dataset_val.load_bowl('../../datastage1_test')
dataset_val.prepare()

#split into train and test groups
#get a list of the image ids from util
image_ids = dataset_train.image_ids
#split the image ids into different groups
random.shuffle(image_ids)

X_train_ids = image_ids[:600]
X_test_ids = image_ids[600:]
print(len(X_train_ids))
print(len(X_test_ids))

X_train = []
X_test = []
for ids in X_train_ids:
    print(ids)
    print(dataset_train.load_image(ids))
    im, im_id = dataset_train.load_image(ids)
    mask, ma_id = dataset_train.load_mask(ids)
    print(im)
```

**Comment by killthekitten** [comment]
Looks like there's a typo in this line:
```python
dataset_val.load_bowl('../../datastage1_test')
```

There should be a slash in the path.

**Comment by killthekitten** [comment]
But the above shouldn't be an issue. Looks like you have the last three lines wrong. `load_image` doesn't return a tuple as you expect and the last element in `load_mask` tuple is `class_id`, not `mask_id` Should be:
```python
    image = dataset_train.load_image(ids)
    mask, class_id = dataset_train.load_mask(ids)
```

Hope this helps.

**Comment by jameschartouni** [comment]
Thanks for the response! I'm getting the error coded posted below with the id 26 for example. Do you think the issue is with the dataset some how being incomplete or improperly formatted on my end?

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-0a7b2b61b1f0> in <module>()
     18     #mask, ma_id = dataset_train.load_mask(ids)
     19     image = dataset_train.load_image(ids)
---> 20     dataset_train.load_mask(ids)
     21     mask, class_id = dataset_train.load_mask(ids)
     22 

~/Music/downloads/Kaggle-data-science-bowl/src/Mask_RCNN-6b390588227fa0215c64879726cf1e2a71afa7cd/bowl_dataset.py in load_mask(self, image_id)
     59 
     60         masks = np.stack(masks, axis=-1)
---> 61         masks = np.where(masks > 128, 1, 0)
     62 
     63         class_ids = np.ones(count)

TypeError: '>' not supported between instances of 'NoneType' and 'int'`

**Comment by jameschartouni** [comment]
I am also getting the same error on the train generator, which leads me to suspect something is wrong with the data.

**Comment by killthekitten** [comment]
Yes, that's definitely about data. Check that png files are under /stage1_train/image_id/masks/*.png and not somewhere else. 

Also, what OS do you use? If you're on windows, then pull the latest master, please. I've merged a fix for the win file paths today.

**Comment by jameschartouni** [comment]
I am using Ubuntu. I used a working dataset, and the same issue persists. Whenever I call load data, or the train_generator calls load_data, none is returned. Why could that be?

**Comment by killthekitten** [comment]
Are you sure you followed the README instructions? I suggested to use a fixed dataset from here https://github.com/lopuhin/kaggle-dsbowl-2018-dataset-fixes

With this dataset, your code works fine for me on the master branch.
